#SPDX-License-Identifier: MIT-0
---
# tasks file for docker

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Create Docker group
  group: 
    name: docker
    state: present

- name: Add user to Docker group
  user: 
    name: "{{ ansible_user }}"
    group: docker
    append: yes
  become: yes

- name: Get ECR login token
  shell: |
    aws ecr get-login-password --region {{ aws_region }} 
  register: ecr_token

- name: Debug ECR Token
  debug: 
    var: ecr_token

- name: Login into ECR registry
  community.docker.docker_login:
    registry_url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
    username: AWS
    password: "{{ ecr_token.stdout }}"
    reauthorize: yes
  register: docker_login_result

- name: Debug ECR Token
  debug: 
    var: docker_login_result

- name: Pull latest Backend image
  docker_image:
    name: "{{ backend_ecr_uri }}:latest"
    source: pull
    force_source: yes

- name: Get SSM Parameter
  shell: |
    aws ssm get-parameter \
    --name "/{{ env_var }}/backend/MONGODB_URI" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region {{ aws_region }}
  register: mongodb_uri


- name: Create .env file from SSM paramenters
  copy: 
    content: |
      MONGODB_URI={{mongodb_uri.stdout }}
      NODE_ENV=production
      PORT=3002
    dest: /opt/todo-app/todo-backend/.env
    mode: "0600"

- name: Start the backend container
  docker_container:
    name: backend
    image: "{{ backend_ecr_uri }}:latest"
    state: started
    restart_policy: always
    ports: 
      - "3002:3002"
    env_file: /opt/todo-app/todo-backend/.env

