---
- name: Provision Ec2 instance & install XX
  hosts: localhost
  gather_facts: no
  roles:
    - ecr_setup

- name: Configuration of Ec2 instances
  hosts: launched_ec2_instances
  vars:
    monitoring_instance_ip: "{{ groups['monitoring_ec2_instances'][0] }}"
  gather_facts: yes
  become: yes
  roles: 
    - common
    - docker
    - otel-collector

- name: Configuration of Monitoring Servers
  hosts: monitoring_ec2_instances
  gather_facts: yes
  become: yes
  roles: 
    - monitoring


    