name: Provision of Ec2 instance and configuration with Ansible

on:
 push:
  branches:
   - main

jobs: 
 provision_ec2:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repo
     uses: actions/checkout@v2

   - name: Setup Python 3.x
     uses: actions/setup-python@v2
     with:
      python-version: "3.10"
      
   - name: Install  dependenies
     run: |
      python -m pip install --upgrade pip
      pip install ansible boto3
      ansible-galaxy collection install amazon.aws 
    
   - name : Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-south-1

   - name: Create SSH Key file
     run : |
       mkdir -p ~/.ssh
       echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
       chmod 600 ~/.ssh/ec2_key.pem
    
   - name: Debug SSH key
     run : ls -l ~/.ssh/ec2_key.pem
    




